version: '3.8'
services:
  app:
    image: turppie/zuko-backend:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/zuko_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=adminadmin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: zuko_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
